{{- if .Values.env }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.app.name }}-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: cluster-secretstore-sample
    kind: ClusterSecretStore
  target:
    name: {{ .Values.app.name }}-secret
    creationPolicy: Owner
  data:
    {{- range .Values.env }}
    {{- if .secret }}
    - secretKey: {{ .name }}
      remoteRef:
        key: {{ .secretName }}
        property: {{ .secretKey }}
    {{- end }}
    {{- end }}
{{- end }}
