namespace: greeter-app
app:
  name: name
  image: juanroldan1989/name:0.0.1
  port: 5001

replicaCount: 1

hpa:
  minReplicas: 1
  maxReplicas: 10

networkPolicy:
  enabled: true
  name: name-ingress-policy
  appLabel: name
  allowedAppLabel: greeter

rollout:
  enabled: true
