namespace: greeter-app
app:
  name: name
  image: juanroldan1989/name:0.0.1
  port: 5001

replicaCount: 2

hpa:
  minReplicas: 2
  maxReplicas: 5

networkPolicy:
  enabled: true
  name: name-ingress-policy
  appLabel: name
  allowedAppLabel: greeter
