namespace: greeter-app
app:
  name: name
  image: juanroldan1989/name:0.0.1
  port: 5001

replicaCount: 3

hpa:
  minReplicas: 3
  maxReplicas: 5

networkPolicy:
  enabled: true
  name: name-ingress-policy
  appLabel: name
  allowedAppLabel: greeter

rollout:
  enabled: false

secrets:
  enabled: true

env:
  - name: DATABASE_URL
    secret: true
    secret_name: "GREETER_SAVER_DATABASE_URL" # kept for reference only
    provider: "AWS_SSM"                       # kept for reference only
