apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: "<base64-encoded-32-byte-key>"  # `head -c 32 /dev/urandom | base64`
      - identity: {} # this fallback allows reading unencrypted secrets;
                     # for example, during initial migration
