apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster-secretstore-sample
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:                       # secretRef is used to authenticate with AWS Secrets Manager
          accessKeyIDSecretRef:          # accessKeyIDSecretRef/secretAccessKeySecretRef are used to authenticate with AWS
            name: awssm-secret
            key: access-key
            namespace: external-secrets  # Namespace where the `awssm-secret` secret is located
          secretAccessKeySecretRef:
            name: awssm-secret
            key: secret-access-key
            namespace: external-secrets
