namespace: greeter-app

app:
  name: greeter-saver
  image: juanroldan1989/greeter-saver:latest
  port: 5008

replicaCount: 3

hpa:
  minReplicas: 3
  maxReplicas: 10

ingress:
  enabled: true

resourceQuota:
  enabled: true

env:
  - name: NAME_SERVICE_URL
    value: "http://name:5001/name"         # non-sensitive env var
  - name: GREETING_SERVICE_URL
    value: "http://greeting:5002/greeting" # non-sensitive env var
  - name: DATABASE_URL
    secret: true                           # if true, the value will be taken from an AWS secret
    secretName: greeter-saver-db           # the name of the secret in AWS
    secretKey: db_url                      # the key of the secret in AWS
  - name: DATABASE_USER
    secret: true
    secretName: greeter-saver-db
    secretKey: db_user
