apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ssm-db-credentials
  namespace: greeter-app
spec:
  provider: aws
  parameters:
    region: us-east-1
    objects: |
      - objectName: "greeter-saver-database-url"
        objectType: "ssmparameter"
  secretObjects:
    - secretName: greeter-saver-secret
      type: Opaque
      data:
        - objectName: "greeter-saver-database-url"
          key: database-url
