apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter
  namespace: greeter-app
  labels:
    app: greeter
spec:
  replicas: 3 # should match minReplicas in manifests/greeter-app/hpa.yaml
  selector:
    matchLabels:
      app: greeter
  template:
    metadata:
      labels:
        app: greeter
    spec:
      containers:
      - name: greeter
        image: juanroldan1989/greeter:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
