apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting
  namespace: greeter-app
  labels:
    app: greeting
spec:
  replicas: 3 # should match minReplicas in manifests/app-a/hpa.yaml
  selector:
    matchLabels:
      app: greeting
  template:
    metadata:
      labels:
        app: greeting
    spec:
      containers:
      - name: greeting
        image: juanroldan1989/greeting:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 5002
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
