apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-custom-app
  namespace: argocd # ArgoCD resource is created in the 'argocd' namespace
spec:
  project: default
  source:
    repoURL: 'https://github.com/juanroldan1989/gitops-manifests-repo'
    targetRevision: main
    path: manifests/application # path to Helm chart
    helm:
      valueFiles:
        - ../custom-app/values.yaml  # overrides for `custom` app
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: custom-app  # Application resources deployed here
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
