apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-external-secrets-operator-config
  namespace: argocd # ArgoCD resource is created in the 'argocd' namespace
spec:
  project: default
  source:
    repoURL: 'https://github.com/juanroldan1989/gitops-manifests-repo'
    targetRevision: main
    path: manifests/bootstrap/external-secrets-operator/config
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
