apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-external-secrets-operator
  namespace: argocd # ArgoCD resource is created in the 'argocd' namespace
spec:
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.15.1 # Or latest stable
    chart: external-secrets
    path: manifests/bootstrap/external-secrets-operator
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
