apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-greeter-saver-app
  namespace: argocd # ArgoCD resource is created in the 'argocd' namespace
spec:
  project: default
  source:
    repoURL: 'https://github.com/juanroldan1989/gitops-manifests-repo'
    targetRevision: main
    path: manifests/base-application # path to Helm chart
    helm:
      valueFiles:
        - ../greeter-saver-app/values.yaml  # overrides for `greeter-saver` app
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: greeter-app # Application resources deployed here
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
